### ISSUE TITLE
我怎么感觉公式都是有问题，甚至还有中文在公式中，乱码吗

### ISSUE THREAD

**Issue by heifeise** [Jas000n/thermo_travelcode#1]

**Comment by heifeise** [comment]
在README中

**Comment by Jas000n** [comment]
https://github.com/Jas000n/thermo_travelcode/blob/master/pics/temperature_compensate_algorithm.png

**Comment by Jas000n** [comment]
因为latex公式在github这里不能正确渲染，我单独截图了。其实这个算法原理很简单，就是估计人脸的大小，计算温度传感器在测温的时候视距内人脸占多少比例，再根据测出的温度和环境温度反推出人脸的温度。有任何问题可以继续联系我。
